### ISSUE TITLE
Field validation in editing tracking

### ISSUE THREAD

**Issue by michaelrachlitz** [thyme-pro/thyme#2]
Case:
As a tool for Jira, I expected the same behaviour when altering trackings, thus I attempted to insert a string "20m" in the number field for minutes. It would be nice if the string was validated and the string would be accepted and converted to a number value internally in Thyme

**Comment by thomasthune** [comment]
Excellent point, fixed in daed9402a24d889c4203aaab43e221f1255eaaf5
